window.EMPIRE_LIMO_CONFIG = {
  businessName: "Empire Executive Limo",
  phoneDisplay: "323-470-1958",
  phoneHref: "+13234701958",
  email: "bookings@empireexecutivelimo.com",
  website: "https://empireexecutivelimo.com",
  hourlyRate: 150,
  minimumHours: 1,
  googleMapsApiKey: "AIzaSyC11ke8krbToLt2n9J0iYoW6BPNFnJdhHw",
  stripeCheckoutUrl: "",
  checkoutApiUrl: "",
  dynamicCheckoutUrl: "",
  paypalCheckoutUrl: "",
  venmoCheckoutUrl: "",
  cashAppPayUrl: "",
};
