window.EMPIRE_LIMO_CONFIG = {
  businessName: "Empire Executive Limo",
  phoneDisplay: "323-470-1958",
  phoneHref: "+13234701958",
  email: "bookings@empireexecutivelimo.com",
  website: "https://empireexecutivelimo.com",
  facebookUrl: "https://www.facebook.com/empireexecutivelimo",
  instagramUrl: "https://www.instagram.com/empireexecutivelimo/",
  hourlyRate: 150,
  minimumHours: 1,
  googleMapsApiKey: "AIzaSyC11ke8krbToLt2n9J0iYoW6BPNFnJdhHw",
  stripeCheckoutUrl: "",
  checkoutApiUrl: "https://empire-limo-checkout.golyalaszlo93.workers.dev/create-checkout",
  bookingStatusUrl: "https://empire-limo-checkout.golyalaszlo93.workers.dev/booking-status",
  leadApiUrl: "https://empire-limo-checkout.golyalaszlo93.workers.dev/lead",
  dynamicCheckoutUrl: "",
  paypalCheckoutUrl: "",
  venmoCheckoutUrl: "",
  cashAppPayUrl: "",
};
